"""baseline schema

Revision ID: f7b18b9a8468
Revises: 
Create Date: 2026-06-13 13:57:42.674751
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b18b9a8468'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('is_publicly_traded', sa.Boolean(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_qsbs_eligible', sa.Boolean(), nullable=False),
    sa.Column('look_through_ticker', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=False)

    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_deductible', sa.Boolean(), nullable=False),
    sa.Column('deduction_category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('family_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('tax_id_encrypted', sa.String(length=500), nullable=True),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('tax_election', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ssn_encrypted', sa.String(length=500), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_comparison_a', sa.Boolean(), nullable=False),
    sa.Column('is_comparison_b', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_allocations_json', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id_encrypted', sa.String(length=500), nullable=True),
    sa.Column('requires_1099', sa.Boolean(), nullable=False),
    sa.Column('vendor_type', sa.String(length=100), nullable=True),
    sa.Column('contact_info', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('account_number_encrypted', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('tax_entity_id', sa.Integer(), nullable=True),
    sa.Column('primary_owner_id', sa.Integer(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_owner_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['tax_entity_id'], ['family_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('required_approver_id', sa.Integer(), nullable=True),
    sa.Column('auto_expire_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['required_approver_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'price_date', name='uq_asset_price_date')
    )
    with op.batch_alter_table('asset_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_prices_asset_id'), ['asset_id'], unique=False)

    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_deductible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['family_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_member_id', sa.Integer(), nullable=False),
    sa.Column('recipient_member_id', sa.Integer(), nullable=True),
    sa.Column('recipient_entity_id', sa.Integer(), nullable=True),
    sa.Column('recipient_external', sa.String(length=300), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('gift_date', sa.Date(), nullable=False),
    sa.Column('fair_market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('donor_cost_basis', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gift_tax_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('annual_exclusion_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lifetime_exemption_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('form_709_filed', sa.Boolean(), nullable=False),
    sa.Column('is_charitable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['donor_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['recipient_entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['recipient_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grat_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('grantor_member_id', sa.Integer(), nullable=False),
    sa.Column('initial_funding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('term_years', sa.Integer(), nullable=False),
    sa.Column('section_7520_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('assumed_growth_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('annuity_payment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remainder_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_savings_estimate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('simulation_params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['grantor_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_summary', sa.String(length=1000), nullable=False),
    sa.Column('action_payload', sa.Text(), nullable=False),
    sa.Column('approver_member_id', sa.Integer(), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.String(length=2000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('langgraph_thread_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['approval_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_member_id', sa.Integer(), nullable=True),
    sa.Column('owner_entity_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('ownership_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['owner_entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['owner_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('is_reversing', sa.Boolean(), nullable=False),
    sa.Column('reversed_entry_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('receipt_path', sa.String(length=500), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('coa_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coa_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_journal_entry_id'), ['journal_entry_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('compliance_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['family_entities.id'], ),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_transaction_id', sa.Integer(), nullable=False),
    sa.Column('original_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_basis_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('original_cost_basis_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_basis_method', sa.String(length=20), nullable=False),
    sa.Column('is_wash_sale_adjusted', sa.Boolean(), nullable=False),
    sa.Column('wash_sale_disallowed_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['acquisition_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_lots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_is_closed'), ['is_closed'], unique=False)

    op.create_table('tax_lot_disposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_lot_id', sa.Integer(), nullable=False),
    sa.Column('sale_transaction_id', sa.Integer(), nullable=False),
    sa.Column('quantity_disposed', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('proceeds_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realized_gain_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_short_term', sa.Boolean(), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('is_wash_sale', sa.Boolean(), nullable=False),
    sa.Column('wash_sale_disallowed', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sale_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['tax_lot_id'], ['tax_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_lot_disposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_lot_disposals_sale_transaction_id'), ['sale_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lot_disposals_tax_lot_id'), ['tax_lot_id'], unique=False)

    op.create_table('wash_sale_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disallowed_disposal_id', sa.Integer(), nullable=False),
    sa.Column('replacement_lot_id', sa.Integer(), nullable=False),
    sa.Column('disallowed_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disallowed_disposal_id'], ['tax_lot_disposals.id'], ),
    sa.ForeignKeyConstraint(['replacement_lot_id'], ['tax_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wash_sale_adjustments')
    with op.batch_alter_table('tax_lot_disposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_lot_disposals_tax_lot_id'))
        batch_op.drop_index(batch_op.f('ix_tax_lot_disposals_sale_transaction_id'))

    op.drop_table('tax_lot_disposals')
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_lots_is_closed'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_asset_id'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_account_id'))

    op.drop_table('tax_lots')
    op.drop_table('compliance_flags')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_journal_entry_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))

    op.drop_table('expenses')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    op.drop_table('ownership')
    op.drop_table('approvals')
    op.drop_table('grat_simulations')
    op.drop_table('gifts')
    op.drop_table('generated_reports')
    op.drop_table('chart_of_accounts')
    with op.batch_alter_table('asset_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_prices_asset_id'))

    op.drop_table('asset_prices')
    op.drop_table('approval_policies')
    op.drop_table('accounts')
    op.drop_table('vendors')
    op.drop_table('investment_profiles')
    op.drop_table('family_members')
    op.drop_table('family_entities')
    op.drop_table('expense_categories')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))

    op.drop_table('assets')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
